### ISSUE TITLE
Heroku app crashes when downloading VR video

### ISSUE THREAD

**Issue by chhayse7en** [mason1901/ikoa-web#12]
Heroku app crashes or restarts itself when downloading VR video (For example : cid = h_1116cabe00090 ). There is no problem when I download the same video locally on PC. The log suggested "Memory quota vastly exceeded". 
[logs-1597402543694.txt](https://github.com/mason1901/ikoa-web/files/5074179/logs-1597402543694.txt)

**Comment by mason1901** [comment]
I changed the concurrent job number from 32 to 16 to fix the memory error.
