### ISSUE TITLE
下载完大于60GB的视频后，显示页无反应，视频未成功上传

### ISSUE THREAD

**Issue by waahaa** [mason1901/ikoa-web#13]
cid：onsd00879,onsd00770,idbd00754
现象：下载完单个视频后，显示页无反应，视频没有成功上传

**Comment by mason1901** [comment]
When the vid download to 100%, the ikoa will call ffmpeg to optimize the vid, but the free dyno has 500MB RAM only, if the size of the vid is too large,  the dyno crashes, so you can't get any response from the page.
I  set the "web_optimized" option to false in the latest version.
