### ISSUE TITLE
Ikoa-web ocassionally fails to download task. Request a feature of retrying the failed tasks.

### ISSUE THREAD

**Issue by chhayse7en** [mason1901/ikoa-web#14]
Please add a feature to retry the failed tasks. Thanks in advance!
![image](https://user-images.githubusercontent.com/69116277/90956840-3e60d100-e4b4-11ea-9c97-c80f2c9920e2.png)

**Comment by mason1901** [comment]
If a vid fails, then there is no need to retry, because ikoa has tried enough times.
