### ISSUE TITLE
App still get banned from Heroku

### ISSUE THREAD

**Issue by chhayse7en** [mason1901/ikoa-web#17]
People who forked the repo should change the repository field in app.json, then deploy your own repo to heroku. 
In a word, use my latest version.

_Originally posted by @mason1901 in https://github.com/mason1901/ikoa-web/issues/16#issuecomment-698058621_

**Comment by chhayse7en** [comment]
forked the repo and changed the repository field in app.json then deployed --> get banned
deployed directly from your latest repo --> still get banned.
**I think Heroku has blacklisted your app like they did to aria2c**

**Comment by mason1901** [comment]
Sign up another heroku account solves the problem.
