### ISSUE TITLE
同一个视频存在不同码率的版本会导致下载失败

### ISSUE THREAD

**Issue by waahaa** [mason1901/ikoa-web#9]
cid：53dv01524,53dv01332,53dv01289,53dv01266,53dv01174,53dv01041

![图像 1](https://user-images.githubusercontent.com/41323324/88471350-0d37c400-cf3b-11ea-9086-11ced9cd7e82.jpg)

![图像 2](https://user-images.githubusercontent.com/41323324/88471352-10cb4b00-cf3b-11ea-8d85-de2cdc9e565d.jpg)

**Comment by mason1901** [comment]
Thanks you, I have fixed the error.
The error happens because the ikoa can't get any input to choose which part of the query results to download. I add `echo 1`  to always choose the first part to download(higher bitrate). It's just a hack, but 
can work anyway.

**Comment by waahaa** [comment]
> Thanks you, I have fixed the error.
> The error happens because the ikoa can't get any input to choose which part of the query results to download. I add `echo 1` to always choose the first part to download(higher bitrate). It's just a hack, but
> can work anyway.

Thanks a lot, bro!
